/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

public class App {

    public static void main(String[] args) {
        //Create the Command line parser
        CommandLineParser parser = new DefaultParser();

        //Create Options
        Options options = new Options();
        options.addOption("h","help", false, "print usage message");
        options.addOption("b","batch", true, "batch file containing expressions to evaluate ");
        options.addOption("o","output", true, "output file");


        try{
            CommandLine line = parser.parse(options, args);

            if(line.hasOption("h")){
                System.out.println("usage: eval [OPTIONS]\n" +
                        "Evaluation of simple mathematical expressions\n" +
                        "\n" +
                        "-b,--batch <file>    batch file containing expressions to evaluate\n" +
                        "-h,--help            print usage message\n" +
                        "-o,--output <file>   output file");
            }else{
                if(line.hasOption("b")){
                    System.out.println("Batch value: " + args[1]);
                }
                if(line.hasOption("o")){
                    System.out.println("Output value: " + args[1]);
                }
            }
        }
        catch(ParseException exp){
            System.out.println(exp);
        }
    }
}
